import { BusinessSettings } from '@tea-nest/types';

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  brandName: 'Tea Nest',
  businessName: 'Fortunate Ventures',
  phone: '+91 98765 43210',
  email: 'fortunateventures123@gmail.com',
  whatsappOrderNumber: '919876543210',
  address: 'Naharkatia, Dist- Dibrugarh',
  city: 'Dibrugarh',
  state: 'Assam',
  pincode: '786610',
  gstin: '18AABCF1234F1Z5',
  pan: 'AABCF1234F',
  currency: 'INR',
  currencySymbol: '₹',
  invoicePrefix: 'INV-2026-',
  startingInvoiceNumber: 1,
  orderPrefix: 'TN-2026-',
  lowStockDefaultPercent: 70,
  terms: '1. Goods once sold will not be taken back unless defective.\n2. Subject to Dibrugarh, Assam jurisdiction.\n3. Keep tea pouches sealed in a cool, dry place away from moisture and strong odors.',
  bankName: 'State Bank of India',
  accountNumber: '38291048291',
  ifsc: 'SBIN0001234',
  upi: 'fortunateventures@sbi',
  orderSettings: {
    allowDirectWhatsapp: true,
    minOrderValue: 0,
    freeShippingThreshold: 999,
    defaultShippingCharge: 50,
  },
  socialMedia: {
    instagram: 'https://instagram.com/teanest.tea',
    facebook: 'https://facebook.com/teanest.tea',
    twitter: 'https://twitter.com/teanest_tea',
  },
  footerContent: 'Handcrafted with reverence in the misty valleys of Naharkatia, Dibrugarh, Assam. A Product from Fortunate Ventures. All rights reserved.',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_PRODUCT_DATA = {
  name: 'Assam Black Tea',
  slug: 'assam-black-tea',
  description: 'Rich • Refreshing • Aromatic. Carefully handpicked from the finest tea gardens of Dibrugarh, our teas are crafted to bring you a pure, refreshing and enriching experience in every cup.',
  sku: 'TN-ABT-500G',
  categoryId: 'black-tea',
  categoryName: 'Black Tea',
  weight: 500,
  unit: 'g' as const,
  mrp: 499,
  sellingPrice: 450,
  purchasePrice: 220,
  gstRate: 5,
  hsnCode: '0902',
  stockQuantity: 100,
  stockReferenceQty: 100,
  lowStockPercent: 70,
  lowStockThresholdQty: 70, // ceil(100 * 70 / 100) = 70
  isPublished: true,
  isFeatured: true,
  isActive: true,
};
